const users=[
    {
        username:'Shivani',
        email:'shivani@gmail.com',
        password:123,
        token:null,
    },
    {
        username:'shivani22',
        email:'shivani22@gmail.com',
        password:123,
        token:null,
    },
    {
        username:'Ram',
        email:'Ram@gmail.com',
        password:123,
        token:null,
    },
    {
        username:'Sita',
        email:'Sita@gmail.com',
        password:123,
        token:null,
    }
  ]
  module.exports=users;